#!/bin/bash
#########################
#   名称: Config
#   用途: 读取配置文件, 修改配置文件
#########################

readonly CONFIG_HERE="$(cd $(dirname ${BASH_SOURCE:-$0});pwd)";

if [ "$Module_Base_Loaded" != true ];then source "$CONFIG_HERE/modules/Base";fi
if [ "$Module_Json_Loaded" != true ];then source "$CONFIG_HERE/modules/Json";fi
if [ "$Module_Json_Statics" != true ];then source "$CONFIG_HERE/modules/Statics";fi

readonly CONFIG="$GAMEROOT/config.json";
readonly CONFIG_VERSION="1";

function ConfigAddMissingKeys()
{
    putinfo "正在更新配置文件...";
    ConfigAddOrSetValue "EnableImeFix" "true";
    ConfigAddKey "Version" "$CONFIG_VERSION";
    putinfo "更新完成";
}

function ConfigAddOrSetValue()
{
    local Key="$1";
    local Value="$2";
    local JsonGet="";

    for ((re=1;re<=3;re++));do
    {
        JsonGet="$(JsonGetValueFromFile "$CONFIG" ".$Key")"
        if [ "$JsonGet" == "null" ] || [ -z "$JsonGet" ] ;then
        {
            ConfigAddKey "$Key" "$Value";
            continue;
        };fi;
    }
	done
}

function ConfigGetValue()
{
    local Key="$1";
    local Value="$(JsonGetValueFromFile "$CONFIG" ".$Key")";
    echo "$Value";
}

function ConfigSetValue()
{
    local Key="$1";
    local Value="$2";

    if [ -z "$Key" ] || [ -z "$Value" ];then
        return 1;
    fi;

    JsonSetValueFromFile "$CONFIG" "$Key" "$Value"
}

function ConfigRemoveKey()
{
    local Key="$1";

    if [ -z "$Key" ];then
        return 1;
    fi;

    JsonRemoveKeyFromFile "$CONFIG" "$Key"
}

function ConfigAddKey()
{
    local Key="$1";
    local Value="$2";

    if [ -z "$Key" ] || [ -z "$Value" ];then
        return 1;
    fi;

    JsonAddKeyFromFile "$CONFIG" "$Key" "$Value"
}

if [ ! -f "$CONFIG" ] || [ "$(JsonTryParseFile "$CONFIG")" != "0" ] ;then
{
    echo "{}" > "$CONFIG";
    ConfigAddMissingKeys;
}
fi;

if [ "$(ConfigGetValue "Version")" != "$CONFIG_VERSION" ];then
{
    ConfigAddMissingKeys;
};fi

readonly Module_Config_Loaded=true;